export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  category: 'eu' | 'associated' | 'third';
}

// EU Member States (27 countries)
export const EU_MEMBER_STATES: Country[] = [
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', category: 'eu' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', category: 'eu' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬', category: 'eu' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷', category: 'eu' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', category: 'eu' },
  { code: 'CZ', name: 'Czechia', dialCode: '+420', flag: '🇨🇿', category: 'eu' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰', category: 'eu' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', flag: '🇪🇪', category: 'eu' },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', category: 'eu' },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', category: 'eu' },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', category: 'eu' },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷', category: 'eu' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', flag: '🇭🇺', category: 'eu' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', category: 'eu' },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', category: 'eu' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', flag: '🇱🇻', category: 'eu' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: '🇱🇹', category: 'eu' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', category: 'eu' },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹', category: 'eu' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', category: 'eu' },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', category: 'eu' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', category: 'eu' },
  { code: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴', category: 'eu' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: '🇸🇰', category: 'eu' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: '🇸🇮', category: 'eu' },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', category: 'eu' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', category: 'eu' },
];

// Horizon Europe Associated Countries
export const ASSOCIATED_COUNTRIES: Country[] = [
  { code: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱', category: 'associated' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', flag: '🇦🇲', category: 'associated' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦', category: 'associated' },
  { code: 'FO', name: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴', category: 'associated' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', flag: '🇬🇪', category: 'associated' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸', category: 'associated' },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', category: 'associated' },
  { code: 'XK', name: 'Kosovo', dialCode: '+383', flag: '🇽🇰', category: 'associated' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', flag: '🇲🇩', category: 'associated' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: '🇲🇪', category: 'associated' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: '🇲🇰', category: 'associated' },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', category: 'associated' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸', category: 'associated' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', category: 'associated' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', category: 'associated' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', category: 'associated' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', category: 'associated' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', category: 'associated' },
];

// Third Countries (comprehensive list)
export const THIRD_COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', category: 'third' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', category: 'third' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩', category: 'third' },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', category: 'third' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', flag: '🇦🇬', category: 'third' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', category: 'third' },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', category: 'third' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿', category: 'third' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸', category: 'third' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', category: 'third' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', category: 'third' },
  { code: 'BB', name: 'Barbados', dialCode: '+1246', flag: '🇧🇧', category: 'third' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', flag: '🇧🇾', category: 'third' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', category: 'third' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯', category: 'third' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', category: 'third' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', category: 'third' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', category: 'third' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', category: 'third' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', category: 'third' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', category: 'third' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', category: 'third' },
  { code: 'CV', name: 'Cabo Verde', dialCode: '+238', flag: '🇨🇻', category: 'third' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', category: 'third' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', category: 'third' },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', category: 'third' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫', category: 'third' },
  { code: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩', category: 'third' },
  { code: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱', category: 'third' },
  { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', category: 'third' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴', category: 'third' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', flag: '🇰🇲', category: 'third' },
  { code: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬', category: 'third' },
  { code: 'CD', name: 'Congo (DRC)', dialCode: '+243', flag: '🇨🇩', category: 'third' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', category: 'third' },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', flag: '🇨🇮', category: 'third' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', category: 'third' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', category: 'third' },
  { code: 'DM', name: 'Dominica', dialCode: '+1767', flag: '🇩🇲', category: 'third' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴', category: 'third' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', category: 'third' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', category: 'third' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻', category: 'third' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶', category: 'third' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: '🇪🇷', category: 'third' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿', category: 'third' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', category: 'third' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯', category: 'third' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', category: 'third' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', flag: '🇬🇲', category: 'third' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', category: 'third' },
  { code: 'GD', name: 'Grenada', dialCode: '+1473', flag: '🇬🇩', category: 'third' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', category: 'third' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳', category: 'third' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼', category: 'third' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', category: 'third' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹', category: 'third' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', category: 'third' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', category: 'third' },
  { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', category: 'third' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', category: 'third' },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', category: 'third' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶', category: 'third' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲', category: 'third' },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', category: 'third' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴', category: 'third' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', category: 'third' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', category: 'third' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', category: 'third' },
  { code: 'KP', name: 'North Korea', dialCode: '+850', flag: '🇰🇵', category: 'third' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷', category: 'third' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', category: 'third' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬', category: 'third' },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', category: 'third' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', category: 'third' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', category: 'third' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷', category: 'third' },
  { code: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾', category: 'third' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', category: 'third' },
  { code: 'MO', name: 'Macao', dialCode: '+853', flag: '🇲🇴', category: 'third' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', category: 'third' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', category: 'third' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', category: 'third' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', category: 'third' },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', category: 'third' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭', category: 'third' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: '🇲🇷', category: 'third' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺', category: 'third' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', category: 'third' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', flag: '🇫🇲', category: 'third' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', category: 'third' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', category: 'third' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', category: 'third' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', category: 'third' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', category: 'third' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', flag: '🇳🇦', category: 'third' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷', category: 'third' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵', category: 'third' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', category: 'third' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', category: 'third' },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', category: 'third' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', category: 'third' },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', category: 'third' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', category: 'third' },
  { code: 'PW', name: 'Palau', dialCode: '+680', flag: '🇵🇼', category: 'third' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', category: 'third' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', category: 'third' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬', category: 'third' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', category: 'third' },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪', category: 'third' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', category: 'third' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', category: 'third' },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺', category: 'third' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', category: 'third' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', flag: '🇰🇳', category: 'third' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1758', flag: '🇱🇨', category: 'third' },
  { code: 'VC', name: 'Saint Vincent', dialCode: '+1784', flag: '🇻🇨', category: 'third' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸', category: 'third' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲', category: 'third' },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flag: '🇸🇹', category: 'third' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', category: 'third' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳', category: 'third' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', category: 'third' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', category: 'third' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', category: 'third' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧', category: 'third' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', flag: '🇸🇴', category: 'third' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', category: 'third' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', flag: '🇸🇸', category: 'third' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', category: 'third' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩', category: 'third' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', category: 'third' },
  { code: 'SY', name: 'Syria', dialCode: '+963', flag: '🇸🇾', category: 'third' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: '🇹🇼', category: 'third' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: '🇹🇯', category: 'third' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿', category: 'third' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭', category: 'third' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱', category: 'third' },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', category: 'third' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴', category: 'third' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹', category: 'third' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲', category: 'third' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', category: 'third' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', category: 'third' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪', category: 'third' },
  { code: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸', category: 'third' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', category: 'third' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿', category: 'third' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', category: 'third' },
  { code: 'VA', name: 'Vatican City', dialCode: '+379', flag: '🇻🇦', category: 'third' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', category: 'third' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', category: 'third' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪', category: 'third' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲', category: 'third' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', category: 'third' },
];

// All countries combined
export const ALL_COUNTRIES: Country[] = [
  ...EU_MEMBER_STATES,
  ...ASSOCIATED_COUNTRIES,
  ...THIRD_COUNTRIES,
];

// Helper function to check if a country is eligible for GEP requirement
// GEP is required only for HES, RES, PUB participants from EU Member States or Associated Countries
export const isEligibleForGEP = (countryName: string): boolean => {
  const country = ALL_COUNTRIES.find(c => c.name === countryName);
  return country?.category === 'eu' || country?.category === 'associated';
};

// Sorted alphabetically for phone code lookup
export const ALL_COUNTRIES_SORTED = [...ALL_COUNTRIES].sort((a, b) => 
  a.name.localeCompare(b.name)
);

// Get category label
export function getCategoryLabel(category: Country['category']): string {
  switch (category) {
    case 'eu': return 'EU Member States';
    case 'associated': return 'Associated Countries';
    case 'third': return 'Third Countries';
  }
}
