project_id = "nfeoyxjstfehwrkgapho"

[functions.lookup-pic]
verify_jwt = false

[functions.deadline-reminders]
verify_jwt = false

[functions.generate-impact-pathway]
verify_jwt = false

[functions.analyse-consortium]
verify_jwt = false

[functions.analyse-feedback]
verify_jwt = false
