import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const sess = JSON.parse(fs.readFileSync('/root/.cache/lovable-auth/session.json','utf8')).session;
const mod = await import('@/integrations/supabase/client');
await (mod.supabase as any).auth.setSession({ access_token: sess.access_token, refresh_token: sess.refresh_token });
const sb = mod.supabase as any;
const PID='11111111-2222-4333-8444-555566667777';
const { data: tpl } = await sb.from('proposal_templates').select('id').eq('proposal_id',PID).maybeSingle();
const { data: sec } = await sb.from('proposal_template_sections').select('id,section_number,title').eq('proposal_template_id',tpl.id).eq('section_number','B1.2').maybeSingle();
console.log('SECTION', sec);
const { fetchSectionBlockTree, buildSectionTypstBody } = await import('@/lib/typst/sectionToTypst');
const { fetchAuthoredFigures } = await import('@/lib/typst/authoredFigures');
const tree = await fetchSectionBlockTree(PID, sec.id);
const figs = await fetchAuthoredFigures(PID, sec.id, { textOnly: true });
console.log('FIGURE BLOCKS', [...figs.blocks.entries()].map(([k,v]:any)=>[k, v.number, v.caption]));
const built = buildSectionTypstBody(tree, { authoredFigures: figs.blocks, sectionLabel: 'B1.2' } as any);
const src = built.source;
const i = src.indexOf('figure');
console.log('SRC AROUND FIGURE:\n', src.slice(Math.max(0,i-1200), i+1500));
