import fs from 'fs';
import * as cheerio from 'cheerio';
const CASE_NAMES = new Set(['Challenges','Case Studies','Lighthouses','Demonstrations','Pilots','Use Cases','Living Labs']);
const defaultSubheads = ['Methodologies','Linked research & innovation activities','Interdisciplinarity','Social sciences & humanities','Gender dimension','Open science practices'];
const expectedIds = ['ed9a2b9d-fc5c-433d-90e3-4ee3fbb8dce0','1de95c79-f6d3-4a4f-bc87-39c7b67d63e1','bbc83a0e-5161-42eb-bc06-940025b5390c','7592098f-8927-4c4f-a51b-9cd805e399f7'];
function norm(s){return (s||'').replace(/\s+/g,' ').trim()}
function count(html){const $=cheerio.load(html,{decodeEntities:false},false);const h3s=$('h3').toArray(); const caseH3s=h3s.filter(el=>CASE_NAMES.has(norm($(el).text()))||!!$(el).attr('data-case-type-heading-id'));return {len:html.length,casesTables:$('[data-cases-table-node]').length,typedCasesTables:$('[data-cases-table-node][data-case-type-id]').length,untypedCasesTables:$('[data-cases-table-node]').length-$('[data-cases-table-node][data-case-type-id]').length,h3Total:h3s.length,caseTypeH3:caseH3s.length,caseTypeH3WithId:caseH3s.filter(el=>!!$(el).attr('data-case-type-heading-id')).length,caseTypeH3ByText:Object.fromEntries([...CASE_NAMES].map(n=>[n,h3s.filter(el=>norm($(el).text())===n).length]).filter(([,v])=>v)),orphanCaseCaptions:$('p.table-caption').toArray().filter(el=>/^Table\s+1\.2\.[a-z]\.?\s+.+/i.test(norm($(el).text())) && !$(el).next().is('table')).length,captionTexts:$('p.table-caption').toArray().map(el=>norm($(el).text())),defaultSubheads:Object.fromEntries(defaultSubheads.map(n=>[n,h3s.filter(el=>norm($(el).text())===n).length])),realTables:$('table').length,userText:['PPI Challenge','ddd','CSNo case lead','cgdschs'].map(t=>[t,norm($.root().text()).includes(t)]),headingIds:$('h3[data-case-type-heading-id]').toArray().map(el=>$(el).attr('data-case-type-heading-id')),tableIds:$('[data-cases-table-node][data-case-type-id]').toArray().map(el=>$(el).attr('data-case-type-id')),idsPersisted: expectedIds.every(id=>$(`h3[data-case-type-heading-id="${id}"]`).length===1 && $(`[data-cases-table-node][data-case-type-id="${id}"]`).length===1)}}
const saved=fs.readFileSync('/tmp/b12wipe/saved_after.html','utf8');
console.log('SAVED', JSON.stringify(count(saved),null,2));
const lines=fs.readFileSync('/tmp/b12wipe/latest_versions.tsv','utf8').trim().split('\n');
for(const line of lines){const tab=line.indexOf('\t'); const v=line.slice(0,tab); const html=line.slice(tab+1); console.log('VERSION', v, JSON.stringify(count(html),null,2));}
