import { readdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const REPO_RAW = 'https://raw.githubusercontent.com/nick-walters/sitra-proposal-studio/main';

const INCLUDE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.sql', '.toml', '.json', '.css', '.html', '.yml', '.yaml',
]);

const INCLUDE_FILES = new Set([
  'package.json', 'tailwind.config.ts', 'vite.config.ts',
  'tsconfig.json', 'tsconfig.app.json', 'tsconfig.node.json',
  'components.json', 'postcss.config.js', 'eslint.config.js',
  'index.html',
]);

const EXCLUDE_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next',
  '.vscode', '.idea', 'coverage', '.lovable', '.cache', 'public',
]);

async function* walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      yield* walk(path);
    } else if (entry.isFile()) {
      yield path;
    }
  }
}

function groupFor(relPath) {
  if (relPath.startsWith('src/pages/admin/')) return 'Admin Pages';
  if (relPath.startsWith('src/pages/')) return 'Pages';
  if (relPath.startsWith('src/components/admin/')) return 'Admin Components';
  if (relPath.startsWith('src/components/participant/')) return 'Participant Components';
  if (relPath.startsWith('src/components/ui/')) return 'UI Components (shadcn)';
  if (relPath.startsWith('src/components/')) return 'Components';
  if (relPath.startsWith('src/hooks/')) return 'Hooks';
  if (relPath.startsWith('src/types/')) return 'Types';
  if (relPath.startsWith('src/lib/')) return 'Lib & Utils';
  if (relPath.startsWith('src/integrations/')) return 'Integrations (Supabase client)';
  if (relPath.startsWith('src/contexts/')) return 'Contexts';
  if (relPath.startsWith('src/data/')) return 'Static data';
  if (['src/App.tsx','src/main.tsx','src/index.css','src/App.css'].includes(relPath)) return 'App entry';
  if (relPath.startsWith('src/')) return 'Other src/';
  if (relPath.startsWith('supabase/functions/')) return 'Edge functions';
  if (relPath.startsWith('supabase/migrations/')) return 'Migrations';
  if (relPath.startsWith('supabase/')) return 'Supabase config';
  if (relPath.startsWith('scripts/')) return 'Build scripts';
  if (relPath.startsWith('.github/')) return 'GitHub workflows';
  return 'Config & root';
}

function shouldInclude(relPath) {
  const filename = relPath.split('/').pop();
  if (INCLUDE_FILES.has(filename)) return true;
  const dot = filename.lastIndexOf('.');
  if (dot === -1) return false;
  return INCLUDE_EXTENSIONS.has(filename.slice(dot));
}

async function build() {
  const files = [];
  for await (const filepath of walk(ROOT)) {
    const rel = relative(ROOT, filepath).replace(/\\/g, '/');
    if (shouldInclude(rel)) files.push(rel);
  }
  files.sort();

  const groups = new Map();
  for (const file of files) {
    const group = groupFor(file);
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(file);
  }

  const order = [
    'App entry', 'Pages', 'Admin Pages',
    'Components', 'Admin Components', 'Participant Components', 'UI Components (shadcn)',
    'Hooks', 'Types', 'Lib & Utils', 'Contexts', 'Integrations (Supabase client)',
    'Static data', 'Other src/',
    'Edge functions', 'Migrations', 'Supabase config',
    'Build scripts', 'GitHub workflows', 'Config & root',
  ];

  const now = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  const lines = [];
  lines.push('# Sitra Proposal Studio — Codebase Manifest');
  lines.push('');
  lines.push('Auto-generated by `.github/workflows/update-context.yml` on every push to `main`. Do not edit by hand.');
  lines.push('');
  lines.push(`_Last updated: ${now} — ${files.length} files_`);
  lines.push('');
  lines.push('For Claude: fetch any raw URL below with WebFetch to read that file\'s current source.');
  lines.push('');

  for (const group of order) {
    const items = groups.get(group);
    if (!items?.length) continue;
    lines.push(`## ${group}`);
    lines.push('');
    for (const file of items) lines.push(`- ${REPO_RAW}/${file}`);
    lines.push('');
  }
  for (const [group, items] of groups) {
    if (order.includes(group)) continue;
    lines.push(`## ${group}`);
    lines.push('');
    for (const file of items) lines.push(`- ${REPO_RAW}/${file}`);
    lines.push('');
  }

  await writeFile(join(ROOT, 'CLAUDE_CONTEXT.md'), lines.join('\n'));
  console.log(`Wrote CLAUDE_CONTEXT.md — ${files.length} files across ${groups.size} groups.`);
}

build().catch(err => { console.error(err); process.exit(1); });
