
-- Add guidelines to Full Proposal template (template_type_id: 33333333-3333-3333-3333-333333333333)

-- A1 General Information guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0002-0001-0000-000000000002', 'official', '', 'Acronym: Enter a short acronym for your proposal (maximum 20 characters). The acronym should be easy to remember and meaningful where possible. It will be used to identify your proposal throughout the evaluation and, if successful, during project implementation.', 1, true),
('00000000-0002-0001-0000-000000000002', 'official', '', 'Title: Enter the full title of your proposal (maximum 200 characters). The title should clearly and concisely describe the main topic and objectives of the project.', 2, true),
('00000000-0002-0001-0000-000000000002', 'official', '', 'Duration: Indicate the proposed duration of the project in months. The duration must be appropriate for the work planned and consistent with the call conditions.', 3, true),
('00000000-0002-0001-0000-000000000002', 'official', '', E'Abstract: Provide a short summary of your proposal (maximum 2000 characters, including spaces). The abstract should include:\n• The main objectives of the project\n• The novelty and ambition of the concept and approach\n• The expected impacts and results\n• A brief description of the methodology\n⚠ The abstract will be published if your proposal is funded. Do not include confidential information.', 4, true),
('00000000-0002-0001-0000-000000000002', 'official', '', 'Keywords: Select up to 5 descriptors from the provided list that best describe the scientific and technical areas of your proposal. You may also add free keywords (maximum 200 characters) for additional precision. Keywords help evaluators and programme managers identify relevant expertise for evaluation.', 5, true),
('00000000-0002-0001-0000-000000000002', 'official', '', 'Previous submission: Indicate whether this proposal (or a very similar one) has been previously submitted under Horizon Europe or Horizon 2020. If yes, provide the proposal number and explain how the proposal has been improved based on any feedback received.', 6, true),
('00000000-0002-0001-0000-000000000002', 'official', '', E'Declarations: The following declarations are made on behalf of all applicants:\n• Consent: All applicants have given explicit consent on their participation and on the content of this proposal\n• Correctness: The information contained in this proposal is correct and complete\n• Eligibility: All applicants comply with eligibility criteria and are not subject to exclusion grounds under the EU Financial Regulation\n• Ethics: The proposal complies with ethical principles and the highest standards of research integrity\n• Civil applications: The proposal has an exclusive focus on civil applications\n⚠ By submitting this proposal, the coordinator confirms these declarations on behalf of all participants.', 7, true),
('00000000-0002-0001-0000-000000000002', 'sitra_tip', 'Crafting an effective acronym', 'Choose an acronym that is memorable, pronounceable, and ideally conveys the essence of your project. Avoid generic terms or overly complex abbreviations. A good acronym helps reviewers and stakeholders remember your project and can become an important part of your project''s brand identity.', 8, true),
('00000000-0002-0001-0000-000000000002', 'sitra_tip', 'Writing a compelling abstract', 'Your abstract is often the first thing evaluators read—make it count. Start with a strong opening sentence that captures the core innovation. Structure it clearly: problem → solution → impact. Avoid jargon and be specific about expected outcomes. Remember this will be published, so make it accessible to a broad audience.', 9, true),
('00000000-0002-0001-0000-000000000002', 'sitra_tip', 'Strategic keyword selection', 'Keywords are used to match proposals with appropriate evaluators. Select keywords that accurately reflect your project''s main scientific/technical domains. Consider using terms that align with the call text and work programme priorities. This helps ensure your proposal is evaluated by experts with relevant background.', 10, true),
('00000000-0002-0001-0000-000000000002', 'sitra_tip', 'Handling previous submissions', 'If resubmitting, be transparent and constructive. Clearly explain how you''ve addressed previous feedback and improved the proposal. Evaluators appreciate seeing genuine evolution of ideas. Even if the previous attempt was under a different call, mention relevant lessons learned.', 11, true);

-- A2 Participants guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0002-0002-0000-000000000002', 'official', '', 'Participant Identification Code (PIC): Each organisation must have a valid 9-digit PIC to participate in Horizon Europe proposals. The PIC is obtained by registering your organisation in the Funding & Tenders Portal Participant Register. The coordinator must verify that all participants are properly registered before submission.', 1, true),
('00000000-0002-0002-0000-000000000002', 'official', '', E'Organisation details: Verify the following information for each participant:\n• Legal name: The official registered name of the organisation\n• Short name: An abbreviated name for easy identification\n• Country: The country where the organisation is legally established\n• Organisation type: Higher/Secondary Education (HES), Research Organisation (RES), Private For-Profit (PRC), Public Body (PUB), International Organisation (INT), or Other (OTH)\n⚠ These details must match the registration in the Participant Register.', 2, true),
('00000000-0002-0002-0000-000000000002', 'official', '', E'Participant roles and status:\n• Beneficiary: Main participant who signs the grant agreement and receives EU funding. Must be a legal entity established in an eligible country.\n• Affiliated entity: Legal entity with a legal or capital link to a beneficiary. May receive part of the grant to carry out project tasks.\n• Associated partner: Contributes to the project but does not receive EU funding.\n• Third party giving in-kind contributions: Provides resources to a beneficiary free of charge.', 3, true),
('00000000-0002-0002-0000-000000000002', 'official', '', 'Consortium composition: For Research and Innovation Actions (RIA) and Innovation Actions (IA), the consortium must include at least 3 independent legal entities from 3 different EU Member States or Associated Countries. Check the specific call conditions for any additional requirements.', 4, true),
('00000000-0002-0002-0000-000000000002', 'official', '', E'Coordinator: Participant number 1 is automatically designated as the coordinator. The coordinator:\n• Acts as the intermediary between the consortium and the European Commission\n• Is responsible for submitting the proposal and managing the grant\n• Receives and distributes EU funding to other beneficiaries\n• Must be established in an EU Member State or Associated Country', 5, true),
('00000000-0002-0002-0000-000000000002', 'official', '', E'Contact persons: Identify the following for each participant:\n• Primary Contact: Receives all official communications regarding the proposal and grant\n• Administrative Contact: Handles administrative matters including legal and financial issues\n• Scientific Contact: Responsible for scientific and technical aspects of the work\n⚠ At least one contact person must be identified for each participant.', 6, true),
('00000000-0002-0002-0000-000000000002', 'official', '', E'Third country participation: Organisations from non-associated third countries may participate under certain conditions:\n• Automatically eligible: Low and middle income countries (as per the Work Programme)\n• Exceptionally eligible: When their participation is essential for the project\n• May participate at own cost: Without EU funding\n⚠ Check the Work Programme for the list of eligible countries and any specific restrictions.', 7, true),
('00000000-0002-0002-0000-000000000002', 'sitra_tip', 'Building a balanced consortium', 'A strong consortium combines complementary expertise across the value chain. Aim for geographic diversity across EU member states and associated countries. Include a mix of research organisations, industry partners (including SMEs), and end-users. Each partner should have a clear, essential role—avoid "passengers" who don''t contribute meaningfully.', 8, true),
('00000000-0002-0002-0000-000000000002', 'sitra_tip', 'Coordinator selection', 'The coordinator (Participant #1) is critical to success. Choose an organisation with strong project management capacity, experience with EU-funded projects, and the administrative resources to handle financial and reporting obligations. The coordinator should be a neutral convener if the consortium includes competing organisations.', 9, true),
('00000000-0002-0002-0000-000000000002', 'sitra_tip', 'Verifying PIC registration', 'Start PIC verification early—new registrations can take several weeks for validation. Ensure all legal information matches official documents exactly. Common issues include mismatched VAT numbers, outdated addresses, or incorrect legal entity types. The coordinator should verify all partner PICs well before the submission deadline.', 10, true),
('00000000-0002-0002-0000-000000000002', 'sitra_tip', 'SME involvement', 'SMEs bring agility, market proximity, and innovation capacity. Horizon Europe has specific targets for SME participation. Clearly identify SME status in the participant list and highlight their unique contributions. SMEs may be eligible for higher funding rates depending on the action type.', 11, true);

-- A3 Budget guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0002-0003-0000-000000000002', 'official', 'Budget model', 'Select either the Standard Budget model (actual costs with 25% flat rate for indirect costs) or the Lump Sum model (if applicable for your call). Check the call conditions to confirm which model applies.', 1, true),
('00000000-0002-0003-0000-000000000002', 'official', 'Personnel costs (Category A)', 'Personnel costs cover employees, natural persons under direct contract, and seconded persons. Calculate based on daily rates and person-months allocated to the project. Include all researchers, technicians, and administrative staff working on the project.', 2, true),
('00000000-0002-0003-0000-000000000002', 'official', 'Subcontracting (Category B)', 'Subcontracting must be justified and clearly identified. Subcontracts should be awarded following best value for money principles. Core project tasks should not normally be subcontracted.', 3, true),
('00000000-0002-0003-0000-000000000002', 'official', 'Purchase costs (Category C)', 'Include travel and subsistence, equipment, and other goods and services. Equipment should be depreciated over the project lifetime unless fully consumed. Travel costs should follow your organisation''s usual practices.', 4, true),
('00000000-0002-0003-0000-000000000002', 'official', 'Other costs & indirect costs', 'Other cost categories include internally invoiced goods and services, and costs of linked third parties. Indirect costs are calculated automatically as 25% of eligible direct costs (excluding subcontracting and in-kind contributions).', 5, true),
('00000000-0002-0003-0000-000000000002', 'official', 'Funding rates', 'RIA (Research and Innovation Actions): 100% funding rate. IA (Innovation Actions): 70% funding rate (100% for non-profit organisations). CSA (Coordination and Support Actions): 100% funding rate.', 6, true);

-- B1.1 Objectives and ambition guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0001-0001-000000000002', 'evaluation', '', 'Clarity and pertinence of the project''s objectives, and the extent to which the proposed work is ambitious, and goes beyond the state of the art.', 0, true),
('00000000-0003-0001-0001-000000000002', 'official', '', E'• Briefly describe the objectives of your proposed work. Why are they pertinent to the work programme topic? Are they measurable and verifiable? Are they realistically achievable?\n• Describe how your project goes beyond the state-of-the-art, and the extent the proposed work is ambitious. Indicate any exceptional ground-breaking R&I, novel concepts and approaches, new products, services or business and organisational models. Where relevant, illustrate the advance by referring to products and services already available on the market. Refer to any patent or publication search carried out.\n• Describe where the proposed work is positioned in terms of R&I maturity (i.e. where it is situated in the spectrum from ''idea to application'', or from ''lab to market''). Where applicable, provide an indication of the Technology Readiness Level, if possible distinguishing the start and by the end of the project.\n⚠ Please bear in mind that advances beyond the state of the art must be interpreted in the light of the positioning of the project. Expectations will not be the same for RIAs at lower TRL, compared with Innovation Actions at high TRLs.', 10, true),
('00000000-0003-0001-0001-000000000002', 'sitra_tip', 'Make objectives SMART', 'Ensure each objective is Specific, Measurable, Achievable, Relevant, and Time-bound. Avoid vague statements like "improve" or "enhance" without quantifiable targets.', 20, true),
('00000000-0003-0001-0001-000000000002', 'sitra_tip', 'Link to EU priorities', 'Explicitly connect your objectives to EU strategic priorities (Green Deal, Digital Decade, etc.). Evaluators look for alignment with broader policy goals.', 21, true),
('00000000-0003-0001-0001-000000000002', 'sitra_tip', 'Technology Readiness Levels (TRL)', E'Where the specific call/topic conditions require a Technology Readiness Level (TRL), the following definitions apply, unless otherwise specified:\n• TRL 1 — Basic principles observed\n• TRL 2 — Technology concept formulated\n• TRL 3 — Experimental proof of concept\n• TRL 4 — Technology validated in a lab\n• TRL 5 — Technology validated in a relevant environment (industrially relevant environment in the case of key enabling technologies)\n• TRL 6 — Technology demonstrated in a relevant environment (industrially relevant environment in the case of key enabling technologies)\n• TRL 7 — System prototype demonstration in an operational environment\n• TRL 8 — System complete and qualified\n• TRL 9 — Actual system proven in an operational environment (competitive manufacturing in the case of key enabling technologies, or in space)', 22, true),
('00000000-0003-0001-0001-000000000002', 'sitra_tip', 'Societal Readiness Levels (SRL)', E'Societal Readiness Level (SRL) is a way of assessing the level of societal adaptation of, for instance, a particular social project, a technology, a product, a process, an intervention, or an innovation (whether social or technical) to be integrated into society.\n\n• SRL 1 – identifying problem and identifying societal readiness\n• SRL 2 – formulation of problem, proposed solution(s) and potential impact, expected societal readiness; identifying relevant stakeholders for the project\n• SRL 3 – initial testing of proposed solution(s) together with relevant stakeholders\n• SRL 4 – problem validated through pilot testing in relevant environment to substantiate proposed impact and societal readiness\n• SRL 5 – proposed solution(s) validated, now by relevant stakeholders in the area\n• SRL 6 – solution(s) demonstrated in relevant environment and in co‐operation with relevant stakeholders to gain initial feedback on potential impact\n• SRL 7 – refinement of project and/or solution and, if needed, retesting in relevant environment with relevant stakeholders\n• SRL 8 – proposed solution(s) as well as a plan for societal adaptation complete and qualified\n• SRL 9 – actual project solution(s) proven in relevant environment', 23, true),
('00000000-0003-0001-0001-000000000002', 'evaluation', '', 'The maximum score for the entire Part B1 is 5 points. The minimum threshold for Part B1 is 4/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);

-- B1.2 Methodology guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0001-0002-000000000002', 'evaluation', '', 'Soundness of the overall methodology.', 0, true),
('00000000-0003-0001-0002-000000000002', 'official', '', E'Describe and explain the overall methodology, referring briefly, where necessary, to the concepts, models and assumptions that underpin your work.\n• Explain how this will enable you to deliver your project''s objectives.\n• When relevant for your project, refer briefly to the aspects below:\n• Any national or international research and innovation activities whose results will feed into the project, and how that link will be established.\n• How expertise and methods from different disciplines will be brought together and integrated in pursuit of your objectives. If you consider that an inter-disciplinary approach is unnecessary in the context of the proposed work, please provide a justification.\n• For topics where the Work Programme indicates the need for the integration of social sciences and humanities, show the role of these disciplines in the project or provide a justification if you consider that these disciplines are not relevant to your proposed project.\n• How the gender dimension (i.e. sex and/or gender analysis) is taken into account in the project''s research and innovation content.\n! This section is mandatory except for topics which have been identified in the work programme as not requiring the integration of the gender dimension into R&I content.\n! Remember that that this question relates to the content of the planned research and innovation activities, and not to gender balance in the teams in charge of carrying out the project.\n• How appropriate open science practices are implemented as an integral part of the proposed methodology. Show how the choice of practices and their implementation are adapted to the nature of your work, in a way that will increase the chances of the project delivering on its objectives.', 1, true),
('00000000-0003-0001-0002-000000000002', 'sitra_tip', 'Use visual methodology diagrams', E'A well-designed methodology flowchart or diagram can communicate your approach more effectively than text alone. Consider including:\n• A high-level overview showing how work packages connect\n• Decision points and feedback loops in your research process\n• How different partner expertise feeds into each phase\nThis helps evaluators quickly grasp the logic of your approach.', 10, true),
('00000000-0003-0001-0002-000000000002', 'sitra_tip', 'Address interdisciplinarity meaningfully', E'Don''t just list disciplines involved - explain HOW they will integrate:\n• Describe specific integration points where disciplines meet\n• Explain the added value of combining these perspectives\n• If claiming interdisciplinarity isn''t needed, provide a strong justification based on the topic requirements\n• Show how you''ll manage potential communication challenges between fields', 11, true),
('00000000-0003-0001-0002-000000000002', 'sitra_tip', 'Gender dimension practical approach', E'The gender dimension refers to research content, not team composition. Ask yourself:\n• Could your research outcomes affect men and women differently?\n• Are there sex-based biological differences relevant to your study?\n• Could gender-related social factors influence your results or their uptake?\n• Have you considered gender in your data collection and analysis?\nIf genuinely not applicable, explain why based on the specific nature of your research.', 12, true),
('00000000-0003-0001-0002-000000000002', 'sitra_tip', 'Open science: be concrete', E'Avoid generic statements about open access. Instead:\n• Specify which outputs will be openly shared and when\n• Name the repositories you''ll use (Zenodo, OpenAIRE, discipline-specific)\n• Explain any legitimate restrictions (IPR, privacy, security)\n• Mention preregistration if applicable to your methodology\n• Consider how open practices will actually improve your research quality', 13, true),
('00000000-0003-0001-0002-000000000002', 'evaluation', '', 'The maximum score for the entire Part B1 is 5 points. The minimum threshold for Part B1 is 4/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);

-- B2.1 Project's pathways towards impact guidelines
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0002-0001-000000000002', 'evaluation', '', 'Credibility of the pathways to achieve the expected outcomes and impacts specified in the work programme, and the likely scale and significance of the contributions due to the project.', 0, true),
('00000000-0003-0002-0001-000000000002', 'official', '', E'The results of your project should make a contribution to the expected outcomes set out for the work programme topic over the medium term, and to the wider expected impacts set out in the ''destination'' over the longer term.\nIn this section you should show how your project could contribute to the outcomes and impacts described in the work programme.\n• Provide a narrative explaining how the project''s results are expected to make a difference in terms of impact, beyond the immediate scope and duration of the project. The narrative should include the components below, tailored to your project.\n(a) Describe the unique contribution your project results would make towards (1) the outcomes specified in this topic, and (2) the wider impacts, in the longer term, specified in the respective destinations in the work programme. Provide quantified estimates where possible and meaningful.\n! Be specific, referring to the effects of your project, and not R&I in general in this field.\n! State the target groups that would benefit.\n(b) Describe any requirements and potential barriers - arising from factors beyond the scope and duration of the project - that may determine whether the desired outcomes and impacts are achieved. These may include, for example, other R&I work within and beyond Horizon Europe; regulatory environment; targeted markets; user behaviour. Indicate if these factors might evolve over time. Describe any mitigating measures you propose.', 1, true),
('00000000-0003-0002-0001-000000000002', 'sitra_tip', 'Be specific about beneficiaries', E'Don''t use vague terms like "society" or "industry". Break down your target groups:\n• Which specific industries or sectors? (e.g., "SMEs in the automotive supply chain" not just "industry")\n• Which population segments? (e.g., "elderly patients with mobility limitations" not just "patients")\n• Which geographic regions will benefit first?\n• Quantify the potential beneficiary population where possible', 10, true),
('00000000-0003-0002-0001-000000000002', 'sitra_tip', 'Create a clear impact pathway', E'Draw a logical chain from your project outputs to ultimate impacts:\nOutputs → Outcomes → Impacts\n• Outputs: What your project directly produces (publications, prototypes, methods)\n• Outcomes: Changes in behaviour/practice by those who use your outputs (within 5 years)\n• Impacts: Wider societal/economic changes (5-10+ years)\nShow credible links at each step, not just aspirational claims.', 11, true),
('00000000-0003-0002-0001-000000000002', 'sitra_tip', 'Address barriers honestly', E'Evaluators value realistic assessments over optimistic claims:\n• Identify 2-3 genuine barriers (regulatory, market, behavioural)\n• Explain why these barriers exist\n• Propose specific mitigation strategies within your control\n• Acknowledge factors outside your control but explain assumptions\nThis demonstrates you understand the real path to impact.', 12, true),
('00000000-0003-0002-0001-000000000002', 'sitra_tip', 'Link explicitly to work programme', E'Your proposal will be evaluated against the specific expected outcomes in the topic:\n• Quote or reference the exact outcomes from the work programme\n• Explain your contribution to EACH listed outcome\n• Use the same terminology as the work programme\n• If you only address some outcomes, acknowledge this and explain why\nDon''t make evaluators guess how your work connects to the call.', 13, true),
('00000000-0003-0002-0001-000000000002', 'evaluation', '', 'The maximum score for the entire Part B2 is 5 points. The minimum threshold for Part B2 is 4/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);

-- B2.2 Measures to maximise impact (Full Proposal only)
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0002-0002-000000000002', 'evaluation', '', 'Suitability and quality of the measures to maximise expected outcomes and impacts, as set out in the dissemination and exploitation plan, including communication activities.', 0, true),
('00000000-0003-0002-0002-000000000002', 'official', '', E'Provide a draft plan for the dissemination and exploitation of the project results (unless the work programme topic explicitly states that such a plan is not required), including:\n• Plan for dissemination and exploitation activities, including identification of results that are expected to be produced and their potential uses. Indicate how the project''s results will be used to create an impact for science, economy, society and policy.\n• Explain how you will create awareness of your project and its results during the project. For this purpose, you will be asked to develop a project website, provide descriptions of your project suitable for non-specialists, prepare regular progress reports, articles and announcements for publication in the media, etc.\n• Identify the most suitable target groups (audiences) for your dissemination and communication activities, be they scientific communities, industry, public authorities, civil society organisations, citizens, policy-makers, or others.\n• Describe the strategy for the protection and management of your intellectual property (IP) throughout the project. Include the conditions under which results will be shared within the consortium and explain how background IP will be identified and protected. If relevant, include considerations about the European interest.', 1, true),
('00000000-0003-0002-0002-000000000002', 'sitra_tip', 'Dissemination vs communication vs exploitation', E'Be clear about the distinction:\n• Dissemination: Sharing results with those who can use them (researchers, industry, policy-makers)\n• Communication: Raising awareness among the general public\n• Exploitation: Actually using the results (commercialisation, policy uptake, further research)\nYour plan should address all three with specific activities and target audiences.', 10, true),
('00000000-0003-0002-0002-000000000002', 'sitra_tip', 'Make exploitation concrete', E'Avoid vague exploitation statements. Instead:\n• Name specific partners who will commercialise results\n• Describe the route to market (licensing, spin-off, product integration)\n• Include realistic timelines for exploitation activities\n• Show how different partners contribute to exploitation\n• Identify potential customers or adopters by name where possible', 11, true),
('00000000-0003-0002-0002-000000000002', 'sitra_tip', 'IP strategy essentials', E'A credible IP strategy should cover:\n• Background IP: What each partner brings and how it''s protected\n• Foreground IP: How new results will be owned and protected\n• Access rights: How partners can use each other''s IP\n• Open access balance: Reconciling open science with commercialisation\nDon''t leave IP to be "decided later"—show you''ve thought it through.', 12, true),
('00000000-0003-0002-0002-000000000002', 'sitra_tip', 'Targeted communication plan', E'Generic communication plans score poorly. Instead:\n• Identify 2-3 priority target audiences beyond the scientific community\n• Describe specific channels to reach each audience\n• Plan concrete activities: workshops, demonstrators, media outreach\n• Allocate sufficient resources (staff time, budget)\n• Consider involving communication professionals', 13, true),
('00000000-0003-0002-0002-000000000002', 'evaluation', '', 'The maximum score for the entire Part B2 is 5 points. The minimum threshold for Part B2 is 4/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);

-- B3.1 Work plan and resources (Full Proposal only)
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0003-0001-000000000002', 'evaluation', '', 'Quality and effectiveness of the work plan, assessment of risks, and appropriateness of the effort assigned to work packages, and the resources overall.', 0, true),
('00000000-0003-0003-0001-000000000002', 'official', '', E'Please provide the following:\n• Brief presentation of the overall structure of the work plan (work packages, dependencies between work packages, timing of deliverables and milestones).\n• Timing of the different work packages and their components (Gantt chart or similar).\n• Detailed work package descriptions (Table 3.1b).\n• Table of deliverables (Table 3.1c).\n• Table of milestones (Table 3.1d).\n• Critical risks and contingency plans (Table 3.1e).\n• Summary of staff effort (Table 3.1f).\n\nThe following tables MUST be completed:\n• Table 3.1a: List of work packages\n• Table 3.1b: Work package description (for each work package)\n• Table 3.1c: List of deliverables\n• Table 3.1d: List of milestones\n• Table 3.1e: Critical risks for implementation\n• Table 3.1f: Summary of staff effort', 1, true),
('00000000-0003-0003-0001-000000000002', 'sitra_tip', 'Work package structure', E'A well-designed WP structure should:\n• Group related activities logically (not just by partner)\n• Include a dedicated management WP (typically WP1)\n• Include dissemination/exploitation as a separate WP\n• Show clear dependencies between WPs\n• Avoid WPs that are too large (>30% of total effort) or too small (<5%)\nEach WP should have a clear, measurable objective.', 10, true),
('00000000-0003-0003-0001-000000000002', 'sitra_tip', 'Deliverables that demonstrate progress', E'Strong deliverables:\n• Are concrete and verifiable (not just "report on progress")\n• Include tangible outputs: prototypes, datasets, software, guidelines\n• Are distributed throughout the project (not all at the end)\n• Have realistic due dates that allow for review and iteration\n• Match the evaluation criteria (show excellence, impact, implementation)', 11, true),
('00000000-0003-0003-0001-000000000002', 'sitra_tip', 'Milestones as decision points', E'Effective milestones:\n• Mark genuine decision points in the project (go/no-go decisions)\n• Have clear, verifiable means of verification\n• Are placed at critical junctures (not arbitrary dates)\n• Include contingency actions if not achieved\n• Don''t duplicate deliverable due dates', 12, true),
('00000000-0003-0003-0001-000000000002', 'sitra_tip', 'Risk management credibility', E'Evaluators want to see:\n• 5-8 genuine technical and non-technical risks\n• Realistic assessment of likelihood and severity\n• Specific mitigation measures (not generic statements)\n• Contingency plans for critical risks\n• Risks that match your project''s actual challenges\nGeneric risk lists suggest lack of real project understanding.', 13, true),
('00000000-0003-0003-0001-000000000002', 'sitra_tip', 'Resource allocation', E'Effort distribution should be:\n• Proportionate to tasks (larger WPs need more PM)\n• Balanced across partners (avoid >40% with one partner unless justified)\n• Front-loaded appropriately for research WPs\n• Realistic for management (typically 5-10% of total)\n• Consistent between WP descriptions and the effort table\nInconsistencies raise red flags.', 14, true),
('00000000-0003-0003-0001-000000000002', 'evaluation', '', 'The maximum score for the entire Part B3 is 5 points. The minimum threshold for Part B3 is 3/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);

-- B3.2 Capacity of participants and consortium (Full Proposal only)
INSERT INTO section_guidelines (section_id, guideline_type, title, content, order_index, is_active) VALUES
('00000000-0003-0003-0002-000000000002', 'evaluation', '', 'Quality and relevant experience of the individual participants, complementarity of the consortium as a whole, and appropriateness of the management structures and procedures.', 0, true),
('00000000-0003-0003-0002-000000000002', 'official', '', E'Describe the consortium. How does it match the project''s objectives, and bring together the necessary disciplinary and inter-disciplinary knowledge? How do the members complement one another (and cover the value chain, where appropriate)?\n• Describe each participant''s relevant experience and role in the project. Provide short profiles (2-3 paragraphs per participant) of the key staff members involved.\n• Describe how the project will be managed. Include the organisational structure and decision-making mechanisms. Identify the Project Coordinator, Work Package Leaders, and any other key roles.\n• Describe the procedures for conflict resolution, intellectual property management, and quality assurance.\n• Explain the approach to equality and diversity in the project team.\n\nFor each participant, the following information MUST be provided:\n• Organisation name and short name\n• Role in the project\n• Key staff involved and their expertise\n• Relevant previous projects/experience', 1, true),
('00000000-0003-0003-0002-000000000002', 'sitra_tip', 'Demonstrate track record', E'For each partner, highlight:\n• Relevant previous EU or national projects\n• Key publications or patents in the field\n• Infrastructure or facilities they bring\n• Specific expertise that others lack\nAvoid generic organisation descriptions—focus on why THIS partner for THIS project.', 10, true),
('00000000-0003-0003-0002-000000000002', 'sitra_tip', 'Key personnel profiles', E'Strong personnel descriptions:\n• Name the actual people who will work on the project\n• Include their relevant qualifications and experience\n• Highlight previous collaborations between key staff\n• Show they have time allocated (not just "involved")\n• Demonstrate continuity (not all junior staff)', 11, true),
('00000000-0003-0003-0002-000000000002', 'sitra_tip', 'Management structure clarity', E'Evaluators need to see:\n• Clear organisational chart with roles and responsibilities\n• Defined decision-making processes (what decisions, who makes them)\n• Conflict resolution mechanisms\n• Quality assurance procedures\n• Risk escalation procedures\nA complex management structure doesn''t mean better management.', 12, true),
('00000000-0003-0003-0002-000000000002', 'sitra_tip', 'Consortium balance', E'Show that your consortium:\n• Covers all required expertise (no gaps)\n• Has appropriate geographic diversity\n• Includes necessary infrastructure/facilities\n• Balances academic research with industry application\n• Has end-users or stakeholders where relevant\nExplain any apparent gaps or overlaps.', 13, true),
('00000000-0003-0003-0002-000000000002', 'evaluation', '', 'The maximum score for the entire Part B3 is 5 points. The minimum threshold for Part B3 is 3/5 and for the proposal as a whole 8/10. This is a general rule, but the topic may state special circumstances.', 200, true);
