REVOKE EXECUTE ON FUNCTION public.acquire_card_lock(uuid, text, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.heartbeat_card_lock(text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.release_card_lock(text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_card_field(uuid, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_manual_text_card(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reorder_card_fields(uuid, uuid[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reorder_section_cards(uuid, uuid[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.restore_card(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.restore_card_field(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.save_card_field_version(uuid, text, text, boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.save_card_text(uuid, text, text, integer, boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.save_card_title(uuid, text, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.seed_proposal_cards(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.soft_delete_card(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.soft_delete_card_field(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.thin_card_field_versions(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_card_bin_retention_on_submit() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_card_deletion_purge_after() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.acquire_card_lock(uuid, text, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.heartbeat_card_lock(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.release_card_lock(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_card_field(uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_manual_text_card(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reorder_card_fields(uuid, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reorder_section_cards(uuid, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.restore_card(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.restore_card_field(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_card_field_version(uuid, text, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_card_text(uuid, text, text, integer, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_card_title(uuid, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.seed_proposal_cards(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.soft_delete_card(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.soft_delete_card_field(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.thin_card_field_versions(uuid) TO authenticated;