UPDATE public.proposal_analyses
SET analysis_data = jsonb_set(analysis_data, '{esr_markdown}', to_jsonb($ESR$# European Commission initial check

The proposal was submitted in time and addresses topic HORIZON-CL4-2026-04-DIGITAL-EMERGING-19 under the Research and Innovation Action (RIA) instrument with an actual-cost budget regime. It is a full-stage submission. The European Commission initial check raises significant concerns: the proposal is manifestly unfinished, with explicit placeholder text in Section 1.1 ("NICK IS WORKING ON THIS!") and Section 2.2 self-flagged as "AI-GENERATED AND REQUIRES HEAVY REVIEW". Part A and Part B are mutually inconsistent (six versus nine work packages, including a WP that exceeds the project's own duration), and the requested EU contribution is listed as €0. On this basis the proposal would in practice be referred for clarification before substantive evaluation, but the panel proceeded to score on the content as submitted.

# 1. Excellence

**Score:** 2.0 / 5 (threshold: 3.0 / 5) — below threshold

The topic — generative AI for drug discovery — is strategically important and well-aligned with European priorities on digital and health sovereignty. The three-pillar logic (industry-defined challenges, industrial integration, community building) is coherent and topic-aligned, and the identification of relevant GenAI method families (protein language models, diffusion architectures, graph neural networks, multi-objective optimisation) is appropriate.

These strengths are, however, decisively outweighed by the state of the submitted text. The proposal is manifestly unfinished: Section 1.1 contains explicit placeholder text and Section 2.2 is self-flagged as AI-generated and unreviewed, so objectives are not formally established. The four pharmaceutical Challenges — the scientific heart of the competition — are referenced but not concretely defined; their endpoints, baselines and success criteria are deferred to WP1, which is inappropriate at full-proposal stage. State-of-the-art benchmarking is generic and asserted rather than demonstrated, with no quantitative baselines, specific datasets, or measurable "beyond-SoTA" targets. The gender dimension in R&I content is not addressed, a notable omission given documented sex and ancestry biases in training data for target biology and drug response. Open science treatment is superficial: a generic DMP deliverable is mentioned, but FAIR strategies for sensitive pharma datasets, model cards, weight and benchmark release, reproducibility standards and open licensing are not elaborated — a critical gap for a GenAI-focused action. Finally, instrument fit is questionable: the action is structured predominantly as an FSTP cascade-funding competition with limited in-consortium knowledge generation, sitting uneasily with the RIA instrument's emphasis on research.

# 2. Impact

**Score:** 2.5 / 5 (threshold: 3.0 / 5) — below threshold

Integration with EIT Health's Headstart (M6) and Bootcamp (M28–M29) programmes is concrete, credible and provides pre-existing commercialisation channels — a genuine differentiator. Industrial anchoring through Bayer and Orion delivers realistic uptake pathways and authentic pharma pull, and the commitment to review at least 30 applicants per Lot for Headstart referral is one of the few concrete KPIs and is welcome. Four impact pathways (scientific frontier, startup commercialisation, pharma competitiveness, ecosystem infrastructure) are articulated across three time horizons.

The impact section is nevertheless explicitly flagged by the applicants as AI-generated and unreviewed, which fundamentally undermines its credibility. Quantified outcome KPIs are largely absent: there are no targets for follow-on investment, licensing deals, patents, validated candidates, publications, open benchmarks, or measurable dissemination reach. IP treatment is superficial despite being pivotal — inventorship and freedom-to-operate for AI-generated molecules, background and foreground allocation between startups and pharma, and data and model licensing are only referenced at headline level. Regulatory pathways (EMA reflection paper on AI/ML), HTA considerations, and the route from AI-generated candidates to clinical validation are not credibly developed, and no wet-lab validation plan is presented. Sustainability beyond the grant ("at least five years") is asserted without a governance or financing model, and no letters of intent or procurement commitments from Bayer or Orion are evidenced. Communication activities targeting patients, civil society and health-system payers are thin despite the healthcare context. As an RIA, Impact is weighted ×1 (standard).

# 3. Implementation

**Score:** 1.5 / 5 (threshold: 3.0 / 5) — below threshold

The consortium is strong and complementary: Sitra (coordination and FSTP experience), EIT Health (pan-European networks and acceleration programmes), Bayer and Orion (pharma end-users and validators), regional health hubs (mentoring), and a catapult and university partner for scientific depth.

The implementation section is otherwise critically deficient. There is a severe internal inconsistency between Part A, which describes a six-WP structure, and Part B Table 3.1a, which lists a nine-WP structure with entirely different titles; one WP (WP2 "Business integration") spans M1–M48, exceeding the 36-month project duration. The work plan is effectively empty: all Part B WPs show zero person-months, no assigned leads (except Sitra on WP9), missing start and end months, blank methodology fields, and "Untitled" tasks, while WP5 text is additionally corrupted with raw MS Word markup. The budget is a disqualifying failure in its own right: the requested EU contribution is listed as **€0**, with no budget table, cost category breakdown, per-partner PM allocation, or FSTP envelope — making resource appropriateness entirely unassessable for an actual-cost RIA in which FSTP would typically dominate cost. The participant list is inconsistent (Medicines Discovery Catapult appears in the narrative but not among the listed participants; participant #3 is labelled "EITH" while referenced elsewhere as a different entity). The risk register is generic and omits risks central to this action: IP disputes over AI-generated inventions, pharma data access and GDPR, FSTP state-aid compliance, competition-law issues in pharma collaboration, regulatory uncertainty for AI-derived candidates, and model reproducibility. Governance structures, decision gates between competition stages, and evaluator-independence arrangements for the challenge are not substantiated, and milestones are not linked to go/no-go criteria.

## Overall panel assessment

ADDGenAI addresses a genuinely strategic European priority with a credible, well-complemented consortium and authentic integration into EIT Health's Headstart and Bootcamp commercialisation pipelines and Bayer/Orion industrial pipelines. However, the submission is manifestly unfinished: it contains explicit placeholder text, self-flagged AI-generated unreviewed sections, two mutually contradictory WP structures (six versus nine WPs, including a WP exceeding the project's own duration), empty methodology and person-month fields, and a €0 requested EU contribution — the last of which alone renders implementation unassessable. Beyond the drafting deficiencies, the action is structurally misaligned with the RIA instrument, functioning as an FSTP cascade-funding competition with minimal in-consortium research, and neither the scientific ambition beyond state of the art nor the concrete challenge definitions are demonstrated. The proposal fails all three thresholds and is not competitive for funding under this call; substantial rework and reconsideration of instrument choice (CSA or IA) would be required before any future resubmission.
$ESR$::text), true)
WHERE id = '84af7c15-4edb-4369-87be-44f6200acbad';